// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthOps struct {
	Login    interface{} `json:"login"`
	Register interface{} `json:"register"`
}

type Category struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type InputCategory struct {
	Name string `json:"name"`
}

type InputProduct struct {
	Name       string `json:"name"`
	CategoryID int64  `json:"categoryId"`
}

type InputUser struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type PageInfo struct {
	StartCursor int64 `json:"startCursor"`
	EndCursor   int64 `json:"endCursor"`
	HasNextPage *bool `json:"hasNextPage"`
}

type Product struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Category   *Category `json:"category"`
	CategoryID *int64    `json:"category_id"`
}
